version: "3.4"

networks:
  simple-chat:
    driver: bridge

services:
  server:
    image: chesterfield10/simple-chat-app:latest
    ports:
      - 50052:50052
    depends_on:
      - etcd
    networks:
      - simple-chat

  etcd:
    image: bitnami/etcd:3.5.0
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - simple-chat