version: "3.4"

networks:
  simple-chat:
    driver: bridge

services:
  server:
    image: chesterfield10/simple-chat-app:latest
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=50052
      - ETCD_SERVER_HOST=etcd
      - ETCD_SERVER_PORT=2379
    ports:
      - 50052:50052
    depends_on:
      - etcd
    networks:
      - simple-chat

  etcd:
    image: bitnami/etcd:3.5.0
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-client:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - simple-chat